### ISSUE TITLE
Test Framework

### ISSUE THREAD

**Issue by ayyaruq** [xivlogs/nari#24]
We currently have no real test framework. As per discussions in Discord, we should start by writing a harness with Python's built in UnitTest module.

**Comment by lunarrize** [comment]
Options are:

* built-in [unittest](https://docs.python.org/3/library/unittest.html) module
* [pytest](https://docs.pytest.org/en/6.2.x/)
* [nose](https://nose.readthedocs.io/en/latest/)

**Comment by lunarrize** [comment]
Fixed by #33
