### ISSUE TITLE
Parsing act event ids 38 and 42 for status effects

### ISSUE THREAD

**Issue by nonowazu** [xivlogs/nari#55]
**Is your feature request related to a problem? Please describe.**
From PR #51, one discussion point is:

> There's 2 statuslist events in ACT: 38 and 42. This covers 38, but we should probably catch the other one too, only real diff is that 42 is just actor ID+name and the status list, without the level, resources, or position.

I feel that adding that parsing in is outside the scope of a pass of adding documentation, so I'm creating the issue.

**Describe the solution you'd like**
I'll let @ayyaruq fill in details

**Describe alternatives you've considered**
/shrug

**Comment by ayyaruq** [comment]
These are effectively the same although idk where they're used since packets don't disambiguate this way. The only real diff is that `42` is likely just for BNPCs while `38` seems to be have changed from everything to just players. Structure is as the comment quoted above says.

**Comment by ayyaruq** [comment]
Handled by #69.
